version: 2.1

jobs:
  test-models:
    docker:
      - image: cimg/python:3.8.10
    environment:
      PYTHONPATH: . 
    steps:
      - checkout
      - run:
          name: "Test models"
          command: |
            pip install -r requirements-test.txt
            pytest -v --disable-warnings

  build:
    docker:
      - image: docker:17.05.0-ce-git

    steps: 
      - checkout
      - setup_remote_docker
      - run:
          name: "Build docker image"
          command: |
            docker build -t $DOCKER_USERNAME/minimal-pipeline .
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push $DOCKER_USERNAME/minimal-pipeline



# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  main-workflow:
    jobs:
      - test-models:
          filters:
            branches:
              only: 
                master
      - build:
          requires:
            - test-models
          filters:
            branches:
              only: 
                master

      
