version: 2.1

jobs:
  test-models:
    docker:
      - image: cimg/python:3.8.10
    environment:
      PYTHONPATH: . 
    steps:
      - checkout
      - run:
          name: "Test models"
          command: |
            pip install -r requirements-test.txt
            pytest -v --disable-warnings

  build:
    docker:
      - image: circleci/cci-demo-docker-primary:0.0.1
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD

    environment:
      PROJECT_NAME: minimal-pipeline

    steps: 
      - checkout
      - setup_remote_docker
      - run:
          name: "Build docker image"
          command: |
            docker build -t $DOCKER_USERNAME/$PROJECT_NAME .
            docker login
            docker push $DOCKER_USERNAME/$PROJECT_NAME:latest


workflows:
  main-workflow:
    jobs:
      - test-models:
          filters:
            branches:
              only: 
                master
      - build:
          requires:
            - test-models
          filters:
            branches:
              only: 
                master

      
